apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: android-emulator
spec:
  replicas: 1 #The number of pods to be created in the Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: android-emulator
  template:
    metadata:
      labels:
        app: android-emulator
    spec:
      #volumes:
      #  - name: report-volume
      #    persistentVolumeClaim:
      #      claimName: report-volume
      containers:
       # Katalon Android Container
        - name: android-emulator #The name of the android emulator container
          image: vaibhavx7/android-emulator:latest #The Docker image for building the android emulator container
      #    volumeMounts:
      #      - mountPath: /katalon_sample_prj/Reports
      #        name: report-volume
          ports:
          - containerPort: 5900 #The port for android emulator container
          args:
            - bash
            - -c
            - |
              ./start_vnc.sh \
              ./start_emu_headed.sh \
              tail -f /dev/null
          env:
            - name: APPIUM_PORT
              value: "4725"
            - name: VNC_PASSWORD
              value: "123"
          securityContext:
              privileged: true
          stdin: true
          tty: true
          
        #   # VNC Container
        # - name: vnc #The name of the VNC container
        #   image: vaibhavx7/android-emulator:latest #The Docker image for building the VNC container
        #   ports:
        #   - containerPort: 5900 #The port for the VNC container
        #   args:
        #     - bash
        #     - -c
        #     - |
        #       ./start_vnc.sh
        #   env:
        #     - name: VNC_PASSWORD
        #       value: "123"
        #   securityContext:
        #       privileged: true
        #   stdin: true
        #   tty: true
